eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
spring:
  application:
    name: uaa-service
#  security:
#    user:
#      name: user
#      roles: admin
#      password: 123456
#    oauth2:
#      resource server:
#        jwt:
#          jwk-set-uri: https://dev-.....okta.com/oauth2/default
  datasource:
    url: "jdbc:mysql://localhost:3306/luban"
    username: admin
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:configserver:http://localhost:7569/
  cloud:
    config:
      uri: http://localhost:7569
    bus:
      enabled: true
  ldap:
    base: "dc=example,dc=com"
    urls: "ldap://localhost:389"
    username: "cn=admin,dc=example,dc=com"
    password: "654321"

github:
  client:
    id: 067b785541c64a642145
    secret: ce71e57bddcecc08d52b593bfa2885ed1d1b4a98
    redirect_uri: http://localhost:7573/login/oauth/redirect

jwt:
  key: dr0u3kqevelp8rmkmojfuoo402

server:
  port: 7572