server:
  port: 7573

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true

jwt:
  key: dr0u3kqevelp8rmkmojfuoo402

spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: uaa_route
          uri: lb://uaa-service
          predicates:
            - Path=/login/**,/uaa/**
        - id: product_route
          uri: lb://product-service
          predicates:
            - Path=/product/**

